# Generated by Django 2.2 on 2019-04-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='UserPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC')),
            ],
            options={
                'verbose_name': 'User place',
                'verbose_name_plural': 'User places',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('flat', models.IntegerField(verbose_name='Apartment number')),
                ('switch_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.SwitchVendor', verbose_name='Vendor of switch')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Model')),
                ('ports', models.PositiveSmallIntegerField(verbose_name='Number of ports')),
                ('switch_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.SwitchVendor', verbose_name='Vendor of switch')),
                ('user_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.UserPlace', verbose_name='User Place')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
    ]
