# Generated by Django 2.2 on 2019-04-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switchmodel',
            options={'ordering': ('title',), 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='switchvendor',
            options={'ordering': ('title',), 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userplace',
            options={'ordering': ('street',), 'verbose_name': 'User place', 'verbose_name_plural': 'User places'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='switch_vendor',
        ),
        migrations.AddField(
            model_name='user',
            name='installation_place',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.UserPlace', verbose_name='Installation place'),
        ),
        migrations.AddField(
            model_name='userplace',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
